"""
TrustCatalog - central configuration.

Every path, weight and threshold used anywhere in the project lives here so
that nothing is hard-coded inside the logic modules.
"""

from pathlib import Path

# ----------------------------------------------------------------------
# PATHS  (pathlib is used everywhere so Windows / Linux both work)
# ----------------------------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent

DATA_DIR = BASE_DIR / "data"
RAW_DIR = DATA_DIR / "raw"            # real Olist CSVs go here
DEMO_DIR = DATA_DIR / "demo"          # synthetic CSVs generated by the project
PROCESSED_DIR = DATA_DIR / "processed"

MODELS_DIR = BASE_DIR / "models"
DATABASE_DIR = BASE_DIR / "database"

DB_PATH = DATABASE_DIR / "trustcatalog.db"
MODEL_PATH = MODELS_DIR / "isolation_forest.joblib"

for _d in (RAW_DIR, DEMO_DIR, PROCESSED_DIR, MODELS_DIR, DATABASE_DIR):
    _d.mkdir(parents=True, exist_ok=True)

# ----------------------------------------------------------------------
# OLIST FILE NAMES (exact names from the Kaggle dataset)
# ----------------------------------------------------------------------
OLIST_FILES = {
    "orders": "olist_orders_dataset.csv",
    "order_items": "olist_order_items_dataset.csv",
    "products": "olist_products_dataset.csv",
    "sellers": "olist_sellers_dataset.csv",
    "reviews": "olist_order_reviews_dataset.csv",
    "customers": "olist_customers_dataset.csv",
    "payments": "olist_order_payments_dataset.csv",
    "geolocation": "olist_geolocation_dataset.csv",
    "category_translation": "product_category_name_translation.csv",
}

# Files the pipeline genuinely needs. Everything else is optional.
REQUIRED_TABLES = ["orders", "order_items"]

# Order statuses that mean "the customer did not get the product".
FAILED_STATUSES = ["canceled", "cancelled", "unavailable"]

# ----------------------------------------------------------------------
# TEMPORAL WINDOWS (early-warning / anti-leakage settings)
# ----------------------------------------------------------------------
# Fraction of the timeline used as the FEATURE WINDOW. Everything after the
# resulting cutoff is the OUTCOME WINDOW used only for evaluation.
FEATURE_WINDOW_FRACTION = 0.75

RECENT_DAYS = 30        # "recent behaviour" sub-window
SHORT_RECENT_DAYS = 7   # very recent activity

# Minimum orders in the feature window for a seller to be scored at all.
MIN_ORDERS_FOR_SCORING = 3

# A seller counts as a positive label if, in the outcome window, this share of
# their orders failed (and they had at least MIN_OUTCOME_ORDERS orders).
OUTCOME_FAILURE_RATE_THRESHOLD = 0.20
MIN_OUTCOME_ORDERS = 3

# ----------------------------------------------------------------------
# RISK SCORING WEIGHTS  (must sum to 1.0)
# ----------------------------------------------------------------------
RISK_WEIGHTS = {
    "behavioral": 0.40,
    "anomaly": 0.30,
    "ghost": 0.20,
    "deterioration": 0.10,
}

# Weights inside the rule-based behavioural score.
BEHAVIOR_WEIGHTS = {
    "cancellation_rate": 0.30,
    "late_delivery_rate": 0.25,
    "shipping_delay": 0.20,
    "delivery_days": 0.10,
    "review_score": 0.10,
    "shipping_limit_breach_rate": 0.05,
}

# Normalisation caps: value at which a feature is considered "as bad as it gets".
BEHAVIOR_CAPS = {
    "cancellation_rate": 0.30,          # 30% cancellations -> full penalty
    "late_delivery_rate": 0.35,
    "shipping_delay": 7.0,              # days from approval to carrier handover
    "delivery_days": 25.0,              # days from purchase to delivery
    "shipping_limit_breach_rate": 0.50,
}

# Weights inside the ghost-listing score.
GHOST_WEIGHTS = {
    "inactivity": 0.25,
    "activity_drop": 0.20,
    "cancellation": 0.20,
    "unavailable": 0.15,
    "shipping_delay": 0.10,
    "late_delivery": 0.10,
}
GHOST_INACTIVE_DAYS_CAP = 45.0

# ----------------------------------------------------------------------
# RISK LEVEL BANDS (configurable)
# ----------------------------------------------------------------------
RISK_BANDS = [
    (0, 30, "LOW"),
    (31, 60, "MEDIUM"),
    (61, 80, "HIGH"),
    (81, 100, "CRITICAL"),
]
HIGH_RISK_THRESHOLD = 61        # >= this is HIGH or CRITICAL
CRITICAL_RISK_THRESHOLD = 81

GHOST_BANDS = [
    (0, 30, "Low concern"),
    (31, 60, "Moderate concern"),
    (61, 80, "High concern"),
    (81, 100, "Critical concern"),
]
GHOST_FLAG_THRESHOLD = 61       # >= this is shown as "Possible Ghost Listing"

# ----------------------------------------------------------------------
# ISOLATION FOREST
# ----------------------------------------------------------------------
ANOMALY_FEATURES = [
    "cancellation_rate",
    "late_delivery_rate",
    "average_delivery_days",
    "average_shipping_delay",
    "average_review_score",
    "orders_per_day",
    "activity_change",
    "delivery_time_variance",
    "shipping_delay_variance",
]

IFOREST_PARAMS = {
    "n_estimators": 200,
    "max_samples": "auto",
    "contamination": "auto",
    "random_state": 42,
    "n_jobs": -1,
}

# The model is fitted on "mostly normal" rows: sellers below this percentile of
# the rule-based behavioural score.
NORMAL_TRAINING_PERCENTILE = 75

# ----------------------------------------------------------------------
# DEMO DATA GENERATION
# ----------------------------------------------------------------------
DEMO_CONFIG = {
    "n_sellers": 120,
    "n_products": 600,
    "n_orders": 9000,
    "n_days": 180,
    "random_seed": 42,
}

# ----------------------------------------------------------------------
# STRESS TEST DEFAULTS (section 13 of the spec)
# ----------------------------------------------------------------------
STRESS_TEST_CONFIG = {
    "n_normal": 40,
    "n_degraded": 10,
    "normal_profile": {
        "cancellation_rate": 0.04,
        "late_delivery_rate": 0.06,
        "average_delivery_days": 4.0,
    },
    "degraded_profile": {
        "cancellation_rate": 0.25,
        "late_delivery_rate": 0.35,
        "average_delivery_days": 11.0,
    },
    "detection_threshold": HIGH_RISK_THRESHOLD,
    "random_seed": 7,
}

PROJECT_NAME = "TRUSTCATALOG"
PROJECT_SUBTITLE = "AI-Powered E-Commerce Integrity & Behavioral Risk Monitor"
